### ISSUE TITLE
shit ton of errors

### ISSUE THREAD

**Issue by ghost** [deadshot465/OwoifyCpp#1]
theres a shit ton of errors in here
![image](https://user-images.githubusercontent.com/96747813/150384702-a1c418e8-77bc-4a82-b14b-490acf9ce79d.png)

**Comment by deadshot465** [comment]
Because the screenshot is too small to see what exactly those errors are, I suppose you're referring to those `inline static const std::wregex`. In that case you need at least C++ 17 to use it.
